services:
  - type: web
    name: freshietg
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: HELIUS_KEY_1
        sync: false
      - key: HELIUS_KEY_2
        sync: false
      - key: HELIUS_KEY_3
        sync: false
      - key: HELIUS_KEY_4
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
